language: python
cache: pip
python:
  - "3.7.3"
install:
  - "python3 -m pip install homeassistant==0.104.1"
script:
  - "mv secrets.yaml.sample secrets.yaml"
  - "rm integrations/customize.yaml"
  - "touch integrations/customize.yaml" #Customize always fails test due to no real zwave network
  - "pip3 install netdisco" 
  - "touch fullchain.pem"
  - "touch privkey.pem"
  - "hass --version"
  - "hass -c . --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'