language: python
cache: pip
python:
  - "3.7.3"
install:
  - "python3 -m pip install homeassistant"
script:
  - "mv secrets.yaml.sample secrets.yaml"
  - "touch fullchain.pem"
  - "touch privkey.pem"
  - "hass --version"
  - "hass -c . --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
