# Welcome to my config file. 
# If you are wondering why its so empty, its 
# because all config files have been split into
# files that do one thing and one thing alone.

# Idea inspried if not outright copyed from Franck Nijhof
# https://github.com/frenck/home-assistant-config

# Loads all the config files 
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
