# Welcome to my config file. Its an ugly mess, but will be cleaned up Someday.

# That someday is today my friends. Current in testing



homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
      name: Authenticator app
    - type: notify
      message: 'Your Home Assistant sign in code is: {}'

  # This will load all yaml files in the intergartions dir
  # I hope
  packages: !include_dir_named integrations


lovelace:
  mode: yaml
# Enables configuration UI
config:

switch:
  - platform: wake_on_lan
    name: "Desktop"
    host: !secret WOL_1_host
    mac: !secret WOL_1_mac
    # https://github.com/home-assistant/home-assistant/pull/28830
    # mac_address: !secret WOL_1_mac

panel_iframe:
  router:
    title: 'OctoPi'
    url: !secret ocotprint_url
    icon: mdi:printer-3d-nozzle

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
     - 'eta'
  binary_sensors:
    monitored_conditions:
     - 'motion_detected'
     - 'person_detected'
     - 'away'
    



unifi:
  controllers:
    - host: unifi
      site: Default
      ssid_filter:
        - !secret main_ssid

octoprint:
  host: !secret ocotprint_hostname
  api_key: !secret ocotprint_api
  name: Prusia i3 MK2.5
  number_of_tools: 1
  bed: true
  
cloud:
  google_actions:
    filter:
      include_domains:
       - light
       - fan
       - lock
      include_entities:
       - input_boolean.sleepmode
       - switch.bedroom_light
       - switch.stairway_light
       

      
#Makes sure Zwave is online before Homekit is
automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homekit.start
  
#Booleans used for Status/Overrides
input_boolean:
   home_occupied:
    name: Is anybody home?
   sleepmode:
    name: Sleep mode
   guestmode:
    name: Guest Override
   motorcyle_tracker:
    name: Motorcycle home
   rikka_override:
    name: Rikka Home Override
    
system_health:

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

logger:
 default: error


influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

    
#Currently in testing phase until I feel it can replace the real system. 
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0