# Welcome to my config file. Its an ugly mess, but will be cleaned up Someday.

# That someday is today my friends. Current in testing




  # This will load all yaml files in the intergartions dir
  # I hope
  packages: !include_dir_named integrations



    
