#Access to TV's via IP contorl
#https://www.home-assistant.io/integrations/vizio/

- platform: vizio
  host: !secret BedroomTV_IP
  access_token: !secret BedroomTV_Token
  name: bedroom_tv_v
- platform: vizio
  host: !secret LivingRoomTV_IP
  access_token: !secret LivingRoomTV_Token
  name: living_room_tv_v


#Merge The Chromecast and Vizio states for the TV into one master media device. 
- platform: universal
  name: Living Room TV
  children: 
   - media_player.living_room_tv_c
   - media_player.living_room_tv_v
  commands:
   turn_on:
    service: media_player.turn_on
    data:
      entity_id: media_player.living_room_tv_v
   turn_off:
    service: media_player.turn_off
    data:
      entity_id: media_player.living_room_tv_v
   select_source:
    service: media_player.select_source
    data_template:
      entity_id: media_player.living_room_tv_v
      source: '{{source}}'
  attributes:
   state: media_player.living_room_tv_v
   source: media_player.living_room_tv_v|source
   source_list: media_player.living_room_tv_v|source_list
   volume_level: media_player.living_room_tv_v|volume_level


- platform: universal
  name: Bedroom TV
  children: 
   - media_player.bedroom_tv_c
   - media_player.bedroom_tv_v
  commands:
   turn_on:
    service: media_player.turn_on
    data:
      entity_id: media_player.bedroom_tv_v
   turn_off:
    service: media_player.turn_off
    data:
      entity_id: media_player.bedroom_tv_v
   select_source:
    service: media_player.select_source
    data_template:
      entity_id: media_player.bedroom_tv_v
      source: '{{source}}'
  attributes:
   state: media_player.bedroom_tv_v
   source: media_player.bedroom_tv_v|source
   source_list: media_player.bedroom_tv_v|source_list
   volume_level: media_player.bedroom_tv_v|volume_level