substitutions:
  device_name: bedroom_tv_plug
  friendly_name: Bedroom TV Plug

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

<<: !include standard_config.yml

sensor:
  # Power measuring sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO16
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current:
      name: ${friendly_name} Current
      filters:
      - calibrate_linear:
        - 10.08 -> 0.165
        - 10.07252 -> 0.5 # This is probably pretty wrong, but I dont have a good way to fix it yet
    voltage:
      name: ${friendly_name} Voltage
    power:
      name: ${friendly_name} Power
      id: power
      filters:
      - calibrate_linear:
        - 41.796 -> 17.5
        - 145.188 -> 60
      force_update: true #For InfluxDB/Grafana
    voltage_divider: 1000     # default 2351
    update_interval: 10s

  - platform: uptime
    name: ${friendly_name} Uptime
    
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s
    

switch:
  - platform: gpio
    id: blue_led #I hope
    pin:
      number: GPIO02
      inverted: True
    restore_mode: ALWAYS_ON
    
  - platform: gpio
    pin: GPIO15
    id: relay
    name: ${friendly_name} Relay
    # Tie Blue LED to relay
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led
    restore_mode: ALWAYS_ON
    
binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: button
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
    internal: True